# Generated by Django 6.0.8 on 2026-08-08 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='marketplace.servicecategorymodel')),
            ],
            options={
                'db_table': 'marketplace_services',
                'indexes': [models.Index(fields=['category', 'is_active'], name='mkt_srv_cat_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='marketplace_services_category_slug_uniq')],
            },
        ),
    ]
