# Generated by Django 6.0.8 on 2026-08-08 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_providermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='marketplace.providermodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='marketplace.servicemodel')),
            ],
            options={
                'db_table': 'marketplace_provider_services',
                'indexes': [models.Index(fields=['provider', 'is_active'], name='mkt_ps_prv_act_idx'), models.Index(fields=['service', 'is_active'], name='mkt_ps_srv_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'service'), name='mkt_prv_srv_uniq')],
            },
        ),
    ]
