# Generated by Django 6.0.8 on 2026-08-08 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_providerservicemodel'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.organizationmodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='marketplace.servicemodel')),
            ],
            options={
                'db_table': 'marketplace_service_requests',
                'indexes': [models.Index(fields=['organization', 'status'], name='mkt_sr_org_status_idx'), models.Index(fields=['service', 'status'], name='mkt_sr_srv_status_idx')],
            },
        ),
    ]
