# Generated by Django 6.0.8 on 2026-08-08 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_servicerequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('max_accesses', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity', to='marketplace.servicerequestmodel')),
            ],
            options={
                'db_table': 'marketplace_opportunities',
            },
        ),
        migrations.CreateModel(
            name='OpportunityAccessModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_accesses', to='marketplace.providermodel')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='marketplace.opportunitymodel')),
            ],
            options={
                'db_table': 'marketplace_opportunity_accesses',
            },
        ),
        migrations.AddIndex(
            model_name='opportunitymodel',
            index=models.Index(fields=['status', 'created_at'], name='mkt_opp_st_cr_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityaccessmodel',
            constraint=models.UniqueConstraint(fields=('opportunity', 'provider'), name='mkt_opp_acc_uniq'),
        ),
    ]
