# Generated by Django 6.0.8 on 2026-08-08 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_opportunitymodel_opportunityaccessmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityInvitationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='marketplace.opportunitymodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_invitations', to='marketplace.providermodel')),
            ],
            options={
                'db_table': 'marketplace_opportunity_invitations',
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'provider'), name='mkt_opp_inv_uniq')],
            },
        ),
    ]
