# Generated by Django 6.0.8 on 2026-08-08 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_opportunityinvitationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityInterestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest', to='marketplace.opportunityinvitationmodel')),
            ],
            options={
                'db_table': 'marketplace_opportunity_interests',
            },
        ),
    ]
