# Generated by Django 6.0.8 on 2026-08-08 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_opportunityinterestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSettlementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('interest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='economic_settlement', to='marketplace.opportunityinterestmodel')),
            ],
            options={
                'db_table': 'marketplace_economic_settlements',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='mkt_settlement_amount_gte_zero')],
            },
        ),
    ]
