# Generated by Django 6.0.8 on 2026-08-08 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_economicsettlementmodel'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWalletModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_wallet', to='organizations.organizationmodel')),
            ],
            options={
                'db_table': 'marketplace_credit_wallets',
            },
        ),
    ]
