# Generated by Django 6.0.8 on 2026-08-08 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_creditwalletmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedgerEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=20)),
                ('units', models.BigIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='marketplace.creditwalletmodel')),
            ],
            options={
                'db_table': 'marketplace_credit_ledger_entries',
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='mkt_wallet_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('units__gt', 0)), name='mkt_credit_ledger_units_gt_zero')],
            },
        ),
    ]
