# Generated by Django 6.0.8 on 2026-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_creditledgerentrymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodel',
            name='requester_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequestmodel',
            name='requester_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequestmodel',
            name='requester_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
