# Generated by Django 6.0.8 on 2026-08-08 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_servicerequestmodel_requester_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityContactReadAuditModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authenticated_user_id', models.UUIDField()),
                ('provider_id', models.UUIDField()),
                ('opportunity_id', models.UUIDField()),
                ('service_request_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'marketplace_opportunity_contact_read_audits',
                'indexes': [models.Index(fields=['provider_id', 'created_at'], name='mkt_opp_cr_prov_idx'), models.Index(fields=['opportunity_id', 'created_at'], name='mkt_opp_cr_opp_idx')],
            },
        ),
    ]
