# Generated by Django 6.0.8 on 2026-08-09 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_opportunitycontactreadauditmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityUnlockPricingConfigurationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.SlugField(unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'marketplace_opportunity_unlock_pricing_configurations',
                'indexes': [models.Index(fields=['scope', 'is_active'], name='mkt_unl_price_scope_act')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='mkt_unlock_price_amount_gt_zero')],
            },
        ),
    ]
