# Generated by Django 6.0.8 on 2026-08-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_opportunityunlockpricingconfigurationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicsettlementmodel',
            name='pricing_configuration_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicsettlementmodel',
            name='pricing_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicsettlementmodel',
            name='pricing_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
