# Generated by Django 6.0.8 on 2026-08-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_economicsettlementmodel_pricing_configuration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodel',
            name='raw_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='marketplace.servicemodel'),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='status',
            field=models.CharField(choices=[('captured', 'Captured'), ('qualifying', 'Qualifying'), ('qualified', 'Qualified'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='captured', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
